name: Build and deploy Flutter app to GitHub Pages
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.7.7' # Puedes cambiar la versión de Flutter aquí
      - name: Build the Flutter app
        run: flutter build web --web-renderer canvaskit --release
      - name: Deploy to GitHub Pages
        uses: bluefireteam/flutter-gh-pages@v7
        with:
          baseHref: /andrea_app_ui/
          workingDir: ./build/web
          webRenderer: canvaskit
